package ru.practicum.android.diploma.vacancy.domain.model

data class VacancyDetail(
    val id: String,
    val name: String,
    val description: String,
    val salaryFrom: Int?,
    val salaryTo: Int?,
    val salaryCurrency: String?,
    val addressCity: String,
    val addressStreet: String,
    val addressBuilding: String,
    val fullAddress: String,
    val experienceId: String,
    val experienceName: String,
    val scheduleId: String,
    val scheduleName: String,
    val employmentId: String,
    val employmentName: String,
    val contactsId: String,
    val contactsName: String,
    val contactsEmail: String,
    val contactsPhone: List<String>?,
    val employerId: String,
    val employerName: String,
    val employerLogo: String?,
    val areaId: Int,
    val areaName: String,
    val areaParentId: Int,
    val skills: List<String>,
    val url: String,
    val industryId: Int,
    val industryName: String
)
